image: noki/maven-xvfb
stages:
  - build
  - test
  - deploy
build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
test_sonar_preview_job:
  stage: test
  except:
    - master
  script:
    - Xvfb :1 -screen 0 1024x768x24 &
    - export DISPLAY=:1
    - mvn --batch-mode verify
test_sonar_job:
  stage: test
  only:
    - master
  script:
    - Xvfb :1 -screen 0 1024x768x24 &
    - export DISPLAY=:1
    - mvn --batch-mode verify
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true -PCI
    - echo "Deploy"