image: noki/maven-xvfb
stages:
  - build
  - test
  - deploy
build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
test_sonar_preview_job:
  stage: test
  except:
    - master
  script:
    - Xvfb :1 -screen 0 1024x768x24 &
    - export DISPLAY=:1
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USERNAME -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME
test_sonar_job:
  stage: test
  only:
    - master
  script:
    - Xvfb :1 -screen 0 1024x768x24 &
    - export DISPLAY=:1
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USERNAME
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true -PDEPLOY_NEXUS_SYNAPTIX
    - echo "Deploy"